### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by soyekwon** [webtoon/dreamstyler#4]
안녕하세요. 
style transfer분야에 관심을 가지고 공부하고 있는 국민대학교 컴퓨터공학과 학생입니다. 
우선, 좋은 연구를 진행해주시고 공개해주신것에 감사드립니다. 

간단하게 inference를 진행해보고 싶은데
FileNotFoundError: [Errno 2] No such file or directory: './outputs/sks03/embedding/final.bin'
다음과 같은 에러로 진행이 불가능한 상황입니다.

혹시 위 파일을 제공해주실 수 있는지 여쭤보고자 issue 남깁니다.

감사합니다!

**Comment by nmhkahn** [comment]
안녕하세요.
체크포인트 파일은 회사 정책 이슈로 공개가 어렵습니다. 이해해주시면 감사하겠습니다.

**Comment by soyekwon** [comment]
넵 감사합니다.
